// Shared client roster.
// "drive" = link to the folder of work samples the founder provided.
// If a client has no drive link yet, their card falls back to their Instagram.
export const CLIENTS = [
  { name: "xdry", category: "Adventure Gear & Towels", handle: "xdry.store", logo: "/logos/xdry.jpg", blurb: "Quick-drying, lightweight ponchos and microfiber towels for the adventure-ready.", drive: "https://drive.google.com/drive/folders/1f416iHPAQ7XoH9AMcPkrAaMsux1RSJQn?usp=drive_link" },
  { name: "Ave Wear", category: "Clothing Brand", handle: "avewear", logo: "/logos/avewear.jpg", blurb: "Everyday clothing brand built on clean, confident style.", drive: "https://drive.google.com/drive/folders/1dMwEXNI5OYcJaLxwwqqfwnvTSZpueKMa?usp=drive_link" },
  { name: "DK Real Estate", category: "Real Estate", handle: "dk.group_", logo: "/logos/dklogo.jpg", blurb: "All about homes — tailored real estate solutions and listings.", drive: "https://drive.google.com/drive/folders/1_FBPD4LbaOVnVasQQvVszx29L8R3F5Y0?usp=drive_link" },
  { name: "Orania Pharmacy", category: "Medical & Health", handle: "oraniapharmacy", logo: "/logos/oraniapharmacy.jpg", blurb: "Trusted neighborhood pharmacy for medical and health essentials.", drive: "https://drive.google.com/drive/folders/1PCuROM4Ylp-Jl6_hC1KazMnXlOSrMX2F?usp=drive_link" },
  { name: "Mitra Real Estate", category: "Real Estate", handle: "mitra.for.realestate", logo: "/logos/mitra.jpg", blurb: "Tailored property solutions in Egypt — sales, resales, and investment opportunities.", drive: "https://drive.google.com/drive/folders/18wVjnYWwnxb3br2uNfFiwM7uf6Rma91D?usp=drive_link" },
  { name: "Ride X", category: "Car Modification", handle: "rriiddeex", logo: "/logos/rridex.jpg", blurb: "Specialized in car modification and protection. Upgrade your ride, stay protected.", drive: "https://drive.google.com/drive/folders/1u67vO0OX42KXoOU-k-eec8Zx6jR_CDhq?usp=drive_link" },
  { name: "Sahartina", category: "Suhour Spot", handle: "sahartina.egy", logo: "/logos/sahartina.jpg", blurb: "Your new favorite suhour spot.", drive: null },
  { name: "Good Furniture", category: "Furniture", handle: "goodfurniture2022", logo: "/logos/goodfurnitur.jpg", blurb: "Quality furniture pieces for every home.", drive: "https://drive.google.com/drive/folders/1AezgdRVT-R1dV1oIZ0mZAhJ03nOXpP_9?usp=drive_link" },
  { name: "World of Scent", category: "Beauty & Personal Care", handle: "world_ofscent", logo: "/logos/worldofscent.jpg", blurb: "Beauty, cosmetics, and personal care essentials.", drive: "https://drive.google.com/drive/folders/1nlL_fMtTIIZBvjNJY4ajEPf3dKrkCGX-?usp=drive_link" },
  { name: "Soffieta Boutique", category: "Fashion Boutique", handle: "soffieta_official", logo: "/logos/soffieta.jpg", blurb: "Wear confidence. Wear Soffieta.", drive: "https://drive.google.com/drive/folders/1RmRB9UPysa1qxySRD_7JlX5f9wEgsMFv?usp=drive_link" },
  { name: "Alles", category: "Luxury Fashion", handle: "alles_eg", logo: "/logos/alles.jpg", blurb: "Elevating your style with luxury pieces.", drive: "https://drive.google.com/drive/folders/1q5RsHlnJp_Hnd6mf3w2LZwnQa_4XKAwX?usp=drive_link" },
  { name: "Future House", category: "Real Estate Marketing", handle: "futurehouseegy", logo: "/logos/future.jpg", blurb: "Dedicated real estate marketing for forward-looking developments.", drive: "https://drive.google.com/drive/folders/1T9GxcyuKOSKY_V-JxCXp4y8pI1BkMUxy?usp=drive_link" },
  { name: "JUDZ", category: "Clothing Brand", handle: "judz.eg", logo: "/logos/judes.jpg", blurb: "A clothing brand with a distinct, modern edge.", drive: null },
  { name: "Revoke", category: "Clothing Brand", handle: "revoke_clo", logo: "/logos/revoke.jpg", blurb: "Minimal, elevated clothing for everyday wear.", drive: "https://drive.google.com/drive/folders/1ItWN0wFOsQ4QE03KswZEPzdpwyt7tAxG?usp=drive_link" },
  { name: "Eissa House", category: "Interior Design", handle: "eissa.house", logo: "/logos/eissahouse.jpg", blurb: "Interior design studio shaping spaces with intention.", drive: "https://drive.google.com/drive/folders/1bJZ4_-yC4Lo1WHuoIJnSoCt1NDUOii68?usp=drive_link" },
  { name: "Your Sofa", category: "Furniture", handle: "your.sofa24", logo: "/logos/yoursofa.jpg", blurb: "Specialists in high-quality sofas and corner sets.", drive: "https://drive.google.com/drive/folders/1EqnTRUaEJ1S5oZEkLNJc_26krHZ9JR3p?usp=drive_link" },
  { name: "Locate", category: "Clothing Store", handle: "locate_egy", logo: "/logos/locate.jpg", blurb: "A clothing store built around modern everyday fashion.", drive: "https://drive.google.com/drive/folders/1qMxKn3pg150tkhhCIYwbAbhJDRcQ0sNi?usp=drive_link" },
  { name: "Bayt Azari", category: "Saudi & Gulf Cuisine", handle: "bayt.azari", logo: "/logos/bayt.jpg", blurb: "Saudi and Gulf cuisine that tastes like home.", drive: null },
  { name: "Glocal", category: "Fashion", handle: "glocal.eg", logo: "/logos/glocal.jpg", blurb: "Local style, global trends.", drive: "https://drive.google.com/drive/folders/1-rZV2SyuHvjCIz1t962FJKrmyDRxp5w8?usp=drive_link" },
];
